package com.example.passportphotocomparisonthesis.Utils

class CONSTANTS{
    companion object{
        val DOC_NUMBER_SUBSTRING_START_INDEX_DOC_TYPE1 = 5
        var DOC_NUMBER_SUBSTRING_END_INDEX_DOC_TYPE1 = 14
        var DOC_NUMBER_CHECK_DIGIT_INDEX_DOC_TYPE1 = 14
        val BIRTH_DATE_SUBSTRING_START_INDEX_DOC_TYPE1 = 0
        var BIRTH_DATE_SUBSTRING_END_INDEX_DOC_TYPE1 = 6
        var BIRTH_DATE_CHECK_DIGIT_INDEX_DOC_TYPE1 = 6
        val EXPIRATION_DATE_SUBSTRING_START_INDEX_DOC_TYPE1 = 8
        var EXPIRATION_DATE_SUBSTRING_END_INDEX_DOC_TYPE1 = 14
        var EXPIRATION_DATE_CHECK_DIGIT_INDEX_DOC_TYPE1 = 14
        var GENDER_INDEX_DOC_TYPE1 = 7
        var DOCUMENT_TYPE_DOC_TYPE1 = 1
        var NAME_SUBSTRING_START_INDEX_DOC_TYPE1 = 0
        var NAME_SUBSTRING_END_INDEX_DOC_TYPE1 = 29
        var NATIONALITY_SUBSTRING_START_INDEX_DOC_TYPE1 = 15
        var NATIONALITY_SUBSTRING_END_INDEX_DOC_TYPE1 = 18


        val DOC_NUMBER_SUBSTRING_START_INDEX_DOC_TYPE2 = 5
        var DOC_NUMBER_SUBSTRING_END_INDEX_DOC_TYPE2 = 9
        var DOC_NUMBER_CHECK_DIGIT_INDEX_DOC_TYPE2 = 9
        val BIRTH_DATE_SUBSTRING_START_INDEX_DOC_TYPE2 = 13
        var BIRTH_DATE_SUBSTRING_END_INDEX_DOC_TYPE2 = 19
        var BIRTH_DATE_CHECK_DIGIT_INDEX_DOC_TYPE2 = 19
        val EXPIRATION_DATE_SUBSTRING_START_INDEX_DOC_TYPE2 = 21
        var EXPIRATION_DATE_SUBSTRING_END_INDEX_DOC_TYPE2 = 27
        var EXPIRATION_DATE_CHECK_DIGIT_INDEX_DOC_TYPE2 = 27
        var GENDER_INDEX_DOC_TYPE2 = 20
        var DOCUMENT_TYPE_DOC_TYPE2 = 2
        var NAME_SUBSTRING_START_INDEX_DOC_TYPE2 = 5
        var NAME_SUBSTRING_END_INDEX_DOC_TYPE2 = 35
        var NATIONALITY_SUBSTRING_START_INDEX_DOC_TYPE2 = 10
        var NATIONALITY_SUBSTRING_END_INDEX_DOC_TYPE2 = 13


        val DOC_NUMBER_SUBSTRING_START_INDEX_DOC_TYPE3 = 5
        var DOC_NUMBER_SUBSTRING_END_INDEX_DOC_TYPE3 = 9
        var DOC_NUMBER_CHECK_DIGIT_INDEX_DOC_TYPE3 = 9
        val BIRTH_DATE_SUBSTRING_START_INDEX_DOC_TYPE3 = 13
        var BIRTH_DATE_SUBSTRING_END_INDEX_DOC_TYPE3 = 19
        var BIRTH_DATE_CHECK_DIGIT_INDEX_DOC_TYPE3 = 19
        val EXPIRATION_DATE_SUBSTRING_START_INDEX_DOC_TYPE3 = 21
        var EXPIRATION_DATE_SUBSTRING_END_INDEX_DOC_TYPE3 = 27
        var EXPIRATION_DATE_CHECK_DIGIT_INDEX_DOC_TYPE3 = 27
        var GENDER_INDEX_DOC_TYPE3 = 20
        var DOCUMENT_TYPE_DOC_TYPE3 = 3
        var NAME_SUBSTRING_START_INDEX_DOC_TYPE3 = 5
        var NAME_SUBSTRING_END_INDEX_DOC_TYPE3 = 43
        var NATIONALITY_SUBSTRING_START_INDEX_DOC_TYPE3 = 10
        var NATIONALITY_SUBSTRING_END_INDEX_DOC_TYPE3 = 13
    }
}